version: '3.8' 

networks:
  shard_network:
    driver: bridge 

services:
  mysql0:
    image: mysql:8.0 
    container_name: mysql0
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: sd_user                        # 생성할 사용자 이름
      MYSQL_PASSWORD: sd_password                # 해당 사용자의 패스워드
    ports:
      - "3306:3306" 
    volumes:
      - shard0_data:/var/lib/mysql 
      - ./mysql_init/shard0.sql:/docker-entrypoint-initdb.d/init.sql:ro 
    networks:
      - shard_network

  mysql1:
    image: mysql:8.0
    container_name: mysql1
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: sd_user                        # 생성할 사용자 이름
      MYSQL_PASSWORD: sd_password                # 해당 사용자의 패스워드
    ports:
      - "3307:3306" 
    volumes:
      - shard1_data:/var/lib/mysql
      - ./mysql_init/shard1.sql:/docker-entrypoint-initdb.d/init.sql:ro 
    networks:
      - shard_network

  mysql2:
    image: mysql:8.0
    container_name: mysql2
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: sd_user                        # 생성할 사용자 이름
      MYSQL_PASSWORD: sd_password                # 해당 사용자의 패스워드
    ports:
      - "3308:3306" 
    volumes:
      - shard2_data:/var/lib/mysql
      - ./mysql_init/shard2.sql:/docker-entrypoint-initdb.d/init.sql:ro 
    networks:
      - shard_network

volumes:
  shard0_data:
  shard1_data:
  shard2_data:
