spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sd_db?serverTimezone=UTC&characterEncoding=UTF-8
    username: sd_user
    password: sd_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    show-sql: true

  cache:
    type: redis

  data:
    redis:
      host: localhost
      port: 6379

# rabbitmq 설정
  rabbitmq:
    host: localhost # RabbitMQ host ip
    port: 5672 # RabbitMQ port
    username: guest # RabbitMQ 웹 관리 콘솔 아이디
    password: guest # RabbitMQ 웹 관리 콘솔 비밀번호

rabbitmq:
  queue:
    name: sample-queue # 사용할 queue 이름
  exchange:
    name: sample-exchange # 사용할 exchange 이름
  routing:
    key: key

management:
  endpoints:
    web:
      exposure:
        include: "*"

cloud:
  aws:
    s3:
      endpoint: http://localhost:9000   # MinIO API 주소
      bucket: sd_images                 # 위에서 만든 버킷 이름
    credentials:
      access-key: sd_admin            # MinIO Access Key
      secret-key: sd_password            # MinIO Secret Key
    region:
      static: us-east-1                 # AWS region처럼 지정 (MinIO는 의미 없음)
    stack:
      auto: false                       # CloudFormation 관련 설정, 꺼도 무방